sudo: required

language: node_js
node_js: 
  - "latest"

cache:
  directories:
    - node_modules

services:
  - docker

before_script:
  - sudo docker build -t wendy/node .
  - sudo docker build --rm -t wendyclima .
  - sudo docker ps -a
  - sudo docker run --rm -it -p 3000:3000 -v $PWD:/app -v /app/node_modules wendyclima

script:
  - npm test