env:
  global:
    - CC_TEST_REPORTER_ID=75ed484a573766914bbc1c29678c28e1196600b85de2e7d0718579354eac2a0d

language: node_js
node_js: 
  - "11"

cache:
  directories:
    - node_modules

before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - npm install

script:
  - npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT