sudo: required

language: node_js

cache:
  directories:
    - node_modules

services:
  - docker

before_install:
- docker build --rm -t wendyclima .
- docker ps -a
- docker run --rm wendyclima npm test