language: node_js
node_js: 
  - "node"

services:
  - docker

before_install:
  - docker build -t wendy/node .
  - docker build --rm -t wendyclima .
  - docker ps -a
  - docker run --rm -it -p 3000:3000 -v $PWD:/app -v /app/node_modules wendyclima

script:
  - npm test