language: node_js
node_js: 
  - "11"

cache:
  directories:
    - node_modules

before_install:
  - npm install

script:
  - npm test
  - npm run-script test-coverage

after_script:
  - ./cc-test-reporter after-build --debug --exit-code $TRAVIS_TEST_RESULT
