sudo: required

language: node_js
node_js: 
  - "11"

services:
  - docker

before_install:
- docker build --rm -t wendyclima .
- docker run --rm -it -p 3000:3000 -v $PWD:/app -v /app/node_modules wendyclima"
- docker ps -a
- docker run -rm wendyclima npm test"

script:
  - npm test