sudo: required

language: node_js
node_js: 
  - "11"

services:
  - docker

before_install:
- docker build -t wendy/test_node .
- docker run -d -p 127.0.0.1:80:4567 wendy/test_node /bin/sh -c "cd /root/sinatra; npm run dev;"
- docker ps -a
- docker run wendy/test_node /bin/sh -c "cd /app; npm test"

script:
  - npm test